AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  daily-report

  Sample SAM Template for daily-report

Globals:
  Function:
    Timeout: 15
    MemorySize: 512

    LoggingConfig:
      LogFormat: JSON

Resources:
  TransactionReportFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: functions/transaction-report.reportHandler
      Runtime: nodejs20.x
      Architectures:
      - x86_64
      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            # Schedule: "cron(0 0 * * ? *)" 
            Schedule: "cron(0/2 * * * ? *)"
            Description: "Trigger Lambda daily"
            Name: "DailyTransactionReport"
            Input: '{"schedule": "daily"}'
        MonthlySchedule:
          Type: Schedule
          Properties:
            Schedule: "cron(0 0 1 * ? *)" 
            Description: "Trigger Lambda monthly"
            Name: "MonthlyTransactionReport"
            Input: '{"schedule": "monthly"}'
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - functions/transaction-report.ts

Outputs:
  TransactionReportFunctionArn:
    Description: "Lambda Function ARN"
    Value: !GetAtt TransactionReportFunction.Arn
